# Generated by Django 3.2.23 on 2024-02-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name_cn', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('name_sn', models.CharField(blank=True, max_length=64, verbose_name='姓名')),
                ('mail', models.CharField(blank=True, max_length=100, verbose_name='邮件')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='籍贯')),
                ('id_card', models.CharField(max_length=128, null=True, verbose_name='身份证号码')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='联系电话')),
                ('department', models.CharField(blank=True, max_length=64, verbose_name='部门')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否员工')),
                ('session_key', models.CharField(blank=True, max_length=128)),
                ('expire_time', models.DateTimeField(null=True, verbose_name='session过期时间')),
                ('position', models.SmallIntegerField(choices=[(1, '创建者'), (10, '员工')], default=1, verbose_name='职位')),
                ('permission_setting', models.SmallIntegerField(choices=[(1, '所有权限'), (2, '部分权限'), (3, '不开放')], default=1, verbose_name='权限设置')),
                ('creator_id', models.IntegerField(null=True, verbose_name='创建者')),
                ('last_editor_id', models.IntegerField(null=True, verbose_name='最后修改者')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
