version: '2.3'
services:
  boss:
    image: crpi-jj52mi82jv24gtu4.cn-hangzhou.personal.cr.aliyuncs.com/dflash/boss:dev
    build:
      context: .
      dockerfile: release/boss.Dockerfile
    restart: always
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mysql
  mysql:
    image: crpi-jj52mi82jv24gtu4.cn-hangzhou.personal.cr.aliyuncs.com/heavycross/mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  nginx:
    restart: always
    image: crpi-jj52mi82jv24gtu4.cn-hangzhou.personal.cr.aliyuncs.com/dflash/nginx:dev
    build:
      context: .
      dockerfile: release/nginx.Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - boss
