# Generated by Django 3.2.23 on 2024-02-02 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.SmallIntegerField(default=0)),
                ('app_id', models.CharField(max_length=20, null=True, verbose_name='第三方appID')),
                ('auth_id', models.CharField(default='', max_length=100, verbose_name='第三方用户id')),
                ('auth_token', models.CharField(default='', max_length=160, verbose_name='token')),
                ('refresh_token', models.CharField(default='', help_text='有这个token的平台是：', max_length=160, verbose_name='token')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('avatar', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=16, null=True, verbose_name='电话')),
                ('email', models.CharField(max_length=128, null=True, verbose_name='邮箱')),
                ('education', models.SmallIntegerField(choices=[(1, '其他'), (2, '初中'), (3, '高中'), (4, '中技'), (5, '中专'), (6, '大专'), (7, '本科'), (8, '硕士'), (9, '博士')], default=1, verbose_name='最高学历')),
                ('school', models.CharField(max_length=200, null=True, verbose_name='毕业院校')),
                ('profession', models.CharField(max_length=200, null=True, verbose_name='所学专业')),
                ('company', models.CharField(max_length=200, null=True, verbose_name='当前公司')),
                ('position', models.CharField(max_length=200, null=True, verbose_name='当前职位')),
                ('experience', models.CharField(max_length=50, null=True, verbose_name='工作年限')),
                ('file', models.CharField(blank=True, max_length=200, null=True, verbose_name='简历附件')),
                ('file_applicant', models.CharField(blank=True, max_length=2000, null=True, verbose_name='申请附件')),
                ('account', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
            options={
                'index_together': {('job_id',), ('account_id',)},
            },
        ),
    ]
