# Generated by Django 3.1.4 on 2024-11-26 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.SmallIntegerField(default=0)),
                ('app_id', models.CharField(max_length=20, null=True, verbose_name='第三方appID')),
                ('auth_id', models.CharField(default='', max_length=100, verbose_name='第三方用户id')),
                ('auth_token', models.CharField(default='', max_length=160, verbose_name='token')),
                ('refresh_token', models.CharField(default='', help_text='有这个token的平台是：', max_length=160, verbose_name='token')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('avatar', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
