# Generated by Django 3.1.4 on 2024-11-28 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('auth_id', models.CharField(default='', max_length=100, verbose_name='第三方用户id')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=3)),
                ('expired_time', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
